tektonDashboard:
  image: gcr.io/tekton-releases/github.com/tektoncd/dashboard/cmd/dashboard:v0.11.1
  replicas: 1
  ingress:
    host:

tektonPipelineController:
  image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.18.1
  replicas: 1
  argsImage:
    kubeconfigWriter: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/kubeconfigwriter:v0.18.1
    creds: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/creds-init:v0.18.1
    git: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.18.1
    entrypoint: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.18.1
    nop: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:v0.18.1
    imagedigestExporter: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/imagedigestexporter:v0.18.1
    pr: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/pullrequest-init:v0.18.1
    buildGcsFetcher: gcr.io/tekton-releases/github.com/tektoncd/pipeline/vendor/github.com/googlecloudplatform/cloud-builders/gcs-fetcher/cmd/gcs-fetcher:v0.18.1
    gsutil: gcr.io/tekton-releases/github.com/tektoncd/cloudsdktool/cloud-sdk:v0.18.1
    shell: gcr.io/distroless/base:debug
  extraArgs: []
  resources: {}

tektonPipelineWebhook:
  image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.18.1
  replicas: 1

tektonTriggersController:
  image: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/controller:v0.11.2
  elImage: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/eventlistenersink:v0.11.2
  replicas: 1

tektonTriggersWebhook:
  image: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/webhook:v0.11.1
  replicas: 1

tektonTriggerInterceptor:
  image: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/interceptors:v0.11.1
  replicas: 1

configDefaults:
  _example: |
    ################################
    #                              #
    #    EXAMPLE CONFIGURATION     #
    #                              #
    ################################

    # This block is not actually functional configuration,
    # but serves to illustrate the available configuration
    # options and document them in a way that is accessible
    # to users that `kubectl edit` this config map.
    #
    # These sample configuration options may be copied out of
    # this example block and unindented to be in the data block
    # to actually change the configuration.

    # default-timeout-minutes contains the default number of
    # minutes to use for TaskRun and PipelineRun, if none is specified.
    default-timeout-minutes: "60"  # 60 minutes

    # default-service-account contains the default service account name
    # to use for TaskRun and PipelineRun, if none is specified.
    default-service-account: "default"

    # default-managed-by-label-value contains the default value given to the
    # "app.kubernetes.io/managed-by" label applied to all Pods created for
    # TaskRuns. If a user's requested TaskRun specifies another value for this
    # label, the user's request supercedes.
    default-managed-by-label-value: "tekton-pipelines"

    # default-pod-template contains the default pod template to use
    # TaskRun and PipelineRun, if none is specified. If a pod template
    # is specified, the default pod template is ignored.
    # default-pod-template:

    # default-cloud-events-sink contains the default CloudEvents sink to be
    # used for TaskRun and PipelineRun, when no sink is specified.
    # Note that right now it is still not possible to set a PipelineRun or
    # TaskRun specific sink, so the default is the only option available.
    # If no sink is specified, no CloudEvent is generated
    # default-cloud-events-sink:

    # default-task-run-workspace-binding contains the default workspace
    # configuration provided for any Workspaces that a Task declares
    # but that a TaskRun does not explicitly provide.
    # default-task-run-workspace-binding: |
    #   emptyDir: {}
