{{- $releaseName := .Release.Name -}}
{{- $servicePort := .Values.httpPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
    app: {{ template "fullname" . }}
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ printf "%s-%s" $releaseName "gitlab" | trunc 63 }}
              servicePort: {{ $servicePort }}
  {{- end }}