apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "fullname" . }}
type: Opaque
data:
  {{ if .Values.config.GITLAB_ROOT_PASSWORD }}
  GITLAB_ROOT_PASSWORD: {{ .Values.config.GITLAB_ROOT_PASSWORD | b64enc | quote }}
  {{ else }}
  GITLAB_ROOT_PASSWORD: {{ randAlphaNum 30 | b64enc | quote }}
  {{ end }}