apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "fullname" . }}
spec:
  selector:
    app: {{ template "fullname" . }}
  ports:
  - name: http
    port: {{ .Values.httpPort | int }}
    targetPort: http