{{- if .Values.horizon.ingress.hosts }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: horizon-listener
spec:
  rules:
  {{- range .Values.horizon.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
      - backend:
          serviceName: el-horizon-listener
          servicePort: 8080
        path: /
  {{- end }}
{{- end }} 