apiVersion: v1
kind: ConfigMap
metadata:
  name: config-defaults
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
data:
  {{- toYaml .Values.configDefaults | nindent 2 }}
