apiVersion: v1
kind: ConfigMap
metadata:
  name: config-artifact-bucket
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
