apiVersion: v1
kind: Service
metadata:
  name: "{{ template "horizon.web" . }}"
  labels:
{{ include "horizon.labels" . | indent 4 }}
spec:
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.port }}
  selector:
{{ include "horizon.matchLabels" . | indent 4 }}
    component: web