apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "horizon.config" . }}
  labels:
{{ include "horizon.labels" . | indent 4 }}
data:
  config: |
{{ tpl (toYaml .Values.config) . | indent 4}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "horizon.roles" . }}
  labels:
{{ include "horizon.labels" . | indent 4 }}
data:
  roles: |
{{ toYaml .Values.roles | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template  "horizon.scopes" .}}
  labels:
{{ include "horizon.labels" . | indent 4 }}
data:
  scopes: |
{{ toYaml .Values.scopes | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template  "horizon.authhtml" .}}
  labels:
{{ include "horizon.labels" . | indent 4 }}
data:
  authhtml:
{{ toYaml .Values.authhtml | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template  "horizon.build_schema" .}}
  labels:
{{ include "horizon.labels" . | indent 4 }}
data:
  build-json-schema.json:
{{ toYaml .Values.build_schema.build_json_schema | indent 4 }}
  build-ui-schema.json:
{{ toYaml .Values.build_schema.build_ui_schema | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template  "horizon.dbinit" .}}
  labels:
{{ include "horizon.labels" . | indent 4 }}
data:
  init.sql: |-
{{ .Files.Get "files/db-init.sql" | indent 4}}
