apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "horizon.job" . }}-{{ .Release.Namespace }}-rolebindings
subjects:
  - kind: ServiceAccount
    name: {{ template "horizon.job" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
