apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clustertriggerbindings.triggers.tekton.dev
  annotations:
    "helm.sh/hook": "pre-install"
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-triggers
    triggers.tekton.dev/release: "v0.10.0"
    version: "v0.10.0"
spec:
  group: triggers.tekton.dev
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
  names:
    kind: ClusterTriggerBinding
    plural: clustertriggerbindings
    singular: clustertriggerbinding
    shortNames:
      - ctb
    categories:
      - tekton
      - tekton-triggers
  subresources:
    status: {}
  version: v1alpha1
