apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: eventlisteners.triggers.tekton.dev
  annotations:
    "helm.sh/hook": "pre-install"
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-triggers
    triggers.tekton.dev/release: "v0.10.0"
    version: "v0.10.0"
spec:
  group: triggers.tekton.dev
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
  names:
    kind: EventListener
    plural: eventlisteners
    singular: eventlistener
    shortNames:
      - el
    categories:
      - tekton
      - tekton-triggers
  # Opt into the status subresource so metadata.generation
  # starts to increment
  subresources:
    status: {}
  version: v1alpha1
  additionalPrinterColumns:
    - name: Address
      type: string
      JSONPath: .status.address.url
    - name: Available
      type: string
      JSONPath: ".status.conditions[?(@.type=='Available')].status"
    - name: Reason
      type: string
      JSONPath: ".status.conditions[?(@.type=='Available')].reason"
