{{- if .Values.core.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "horizon.core" . }}
  labels:
{{ include "horizon.labels" . | indent 4 }}
  {{- with .Values.core.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
